version: "3.9"

services:

  ai-service:
    build:
      context: ./Backend/ai-service
    ports:
      - "8000:8000"
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - ai-service
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    environment:
    - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

# frontend:
#   build: ./frontend
#   ports:
#     - "5173:5173"
#   volumes:
#     - ./frontend:/app
#     - /app/node_modules
#   command: npm run dev -- --host